name: Trigger Shock Workflow

on:
  workflow_dispatch:
    inputs:
      shock_id:
        description: 'Shock ID to trigger'
        required: true
        default: 'default_shock_id'  # Replace with a default value for manual runs if wanted
      intensity:
        description: 'Intensity of the shock'
        required: true
        default: '50'
      duration:
        description: 'Duration of the shock in milliseconds'
        required: true
        default: '1000'
  schedule:
    - cron: '59 23 31 2 *' # Change this to your desired schedule

jobs:
  trigger-shock:
    runs-on: ubuntu-latest
    steps:
      - name: Trigger Shock
        uses: ./.github/actions/trigger-shock
        with:
          shock_id: ${{ github.event.inputs.shock_id || env.SHOCK_ID }}
          intensity: ${{ github.event.inputs.intensity || env.INTENSITY }}
          duration: ${{ github.event.inputs.duration || env.DURATION }}
