name: ⚡️ Trigger Shock Workflow

on:
  workflow_dispatch:
    inputs:
      shocker_id:
        description: 'Shocker ID to trigger'
        required: true
        default: '3fa85f64-5717-4562-b3fc-2c963f66afa6'  # Replace with a default value for manual runs if wanted
      intensity:
        description: 'Intensity of the shock'
        required: true
        default: '50'
      duration:
        description: 'Duration of the shock in milliseconds'
        required: true
        default: '1000'
  schedule:
    - cron: '59 23 31 2 *' # Change this to your desired schedule

jobs:
  trigger-shock:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      - name: Trigger Shock
        uses: ./.github/actions/trigger-shock
        with:
          shocker_id: ${{ github.event.inputs.shocker_id || vars.SHOCKER_ID }}
          intensity: ${{ github.event.inputs.intensity || vars.INTENSITY }}
          duration: ${{ github.event.inputs.duration || vars.DURATION }}
          api_key: ${{ secrets.API_KEY }}
